[package]
name = "cdda-item-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.27.2"
egui = "0.27.2"
native-dialog = "0.7.0"
nfd = "0.0.4"
serde = "1.0.203"
serde_json = "1.0.117"
walkdir = "2.5.0"
